<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/accessingElements_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [4]:
print("a[0]=",a[0])
print("a[4]=",a[4])
print("a[-1]=",a[-1])
print("a[-4]=",a[-4])

a[0]= 10
a[4]= 50
a[-1]= 60
a[-4]= 30


In [5]:
b=np.array([[10,20,30,40],[50,60,70,80]])
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [6]:
print("b[0,1]=",b[0,1])

b[0,1]= 20


In [8]:
print("b[0,2]=",b[0,2])

b[0,2]= 30


In [9]:
print("b[-1,-2]=",b[-1,-2])

b[-1,-2]= 70


In [11]:
c=np.array([[[10,20,30],[15,20,50]],
[[10,1,25],[5,10,25]]])

In [12]:
print(c)

[[[10 20 30]
  [15 20 50]]

 [[10  1 25]
  [ 5 10 25]]]


In [13]:
print("c[0,1,1]=",c[0,1,1])

c[0,1,1]= 20


In [14]:
print("c[1,1,2]=",c[1,1,2])

c[1,1,2]= 25


In [15]:
print("c[-1,1,-3]=",c[-1,1,-3])

c[-1,1,-3]= 5


In [18]:
print("c[-1,0,-3]=",c[-1,0,-3])

c[-1,0,-3]= 10
