<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/arange_linspace_logspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# arange function in numpy
#np.arange(start index, stop index, step size, datatype)


# np.linspace(start index, stop index, num, endpoint,return step, dtype)

# start index-lower boundary
# stop index-upper boundary
# num = Number of required values in array
#  It is optional
# default=50

# endpoint = True, stop index will be included
          #  =false, stop index will not be included
          # optional/default=True

# return step = it returns difference between values.
              # optional
              # if it is True, Value will be visible
              # if is False, value will not be visible.
# by default it will be false


# np.logspace(start index, stop index, num, endpoint, base,dtype)
#  start index=lower bound

# stop index = upper bound

# num= number of values required /default=50

# endpoint,if it is True, endpoint will be visible
          #  if it is False, endpoint will not be visible
          # optional/default=True

# base= Base of log values
      # default=True

      





In [9]:
import numpy as np
print(np.arange(0,10,2,dtype="int"))

[0 2 4 6 8]


In [10]:
arr=np.arange(0,10,2,dtype="int")

In [8]:
print(arr)

[0 3 6 9]


In [11]:
arr=np.arange(0,10,2,dtype="float")

In [12]:
print(arr)

[0. 2. 4. 6. 8.]


In [13]:
arr1=np.linspace(0,10,5,retstep=True,dtype="float")

In [14]:
print(arr1)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


In [15]:
arr2=np.linspace(0,10,retstep=True,dtype="float")

In [16]:
print(arr2)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]), 0.20408163265306123)


In [20]:
arr3=np.logspace(0,20,5)

In [21]:
print(arr3)

[1.e+00 1.e+05 1.e+10 1.e+15 1.e+20]


In [22]:
arr3=np.logspace(1,10,endpoint=False)

In [23]:
print(arr3)

[1.00000000e+01 1.51356125e+01 2.29086765e+01 3.46736850e+01
 5.24807460e+01 7.94328235e+01 1.20226443e+02 1.81970086e+02
 2.75422870e+02 4.16869383e+02 6.30957344e+02 9.54992586e+02
 1.44543977e+03 2.18776162e+03 3.31131121e+03 5.01187234e+03
 7.58577575e+03 1.14815362e+04 1.73780083e+04 2.63026799e+04
 3.98107171e+04 6.02559586e+04 9.12010839e+04 1.38038426e+05
 2.08929613e+05 3.16227766e+05 4.78630092e+05 7.24435960e+05
 1.09647820e+06 1.65958691e+06 2.51188643e+06 3.80189396e+06
 5.75439937e+06 8.70963590e+06 1.31825674e+07 1.99526231e+07
 3.01995172e+07 4.57088190e+07 6.91830971e+07 1.04712855e+08
 1.58489319e+08 2.39883292e+08 3.63078055e+08 5.49540874e+08
 8.31763771e+08 1.25892541e+09 1.90546072e+09 2.88403150e+09
 4.36515832e+09 6.60693448e+09]
