<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/arthmetic_operations_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
b=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [4]:
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
np.shape(a)

(3, 3)

In [6]:
np.shape(b)

(3, 3)

In [7]:
np.add(a,b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
c=np.array([10,20,30])

In [9]:
np.shape(c)

(3,)

In [10]:
np.add(a,c)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [11]:
d=np.array([10,20])

In [12]:
np.shape(d)

(2,)

In [13]:
np.add(a,d)

ValueError: ignored

In [14]:
e=np.array([10])

In [15]:
np.shape(e)

(1,)

In [16]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
np.add(a,e)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
np.subtract(a,e)

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [19]:
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.subtract(a,b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.multiply(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.divide(a,b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [25]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(c)

[10 20 30]


In [27]:
np.power(a,c)

array([[                   1,              1048576,      205891132094649],
       [             1048576,       95367431640625,  8138741398091333632],
       [           282475249,  1152921504606846976, -3535985420588157519]])

In [28]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.mod(a,3)

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [30]:
np.power(a,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [32]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
np.mod(a,10)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:

np.reciprocal(a)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
f=np.array([0.5,0.3,0.4])

In [37]:
np.reciprocal(f)

array([2.        , 3.33333333, 2.5       ])

In [38]:
complex=np.array([5+6j,10-5j,9+7j])

In [39]:
complex

array([ 5.+6.j, 10.-5.j,  9.+7.j])

In [40]:
np.real(complex)

array([ 5., 10.,  9.])

In [41]:
np.imag(complex)

array([ 6., -5.,  7.])

In [42]:
np.conjugate(complex)

array([ 5.-6.j, 10.+5.j,  9.-7.j])