<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
my_list= [x * 10 for x in range(1,11)]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
my_array.ndim

1

In [7]:
my_array.shape

(10,)

In [8]:
my_array.size

10

In [9]:
my_array.dtype

dtype('int64')

In [11]:
my_array.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [12]:
my_array.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])