<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/axis_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Axis-0 means Column
# Axis-1 means Row

In [2]:
import numpy as np


In [3]:
a=np.array([[40,20,30],[90,30,40]])


In [4]:
a

array([[40, 20, 30],
       [90, 30, 40]])

In [6]:
np.sort(a,axis=0)

array([[40, 20, 30],
       [90, 30, 40]])

In [8]:
b=np.array([[10,20,15],[5,10,25]])
np.sort(b,axis=0)   #[5,10,15]
                    #  [10,20,25]

array([[ 5, 10, 15],
       [10, 20, 25]])

In [9]:
c=np.array([[1,2,3,4],[6,7,8,9]])
np.sort(c,axis=0)

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [12]:
d=np.array([[25,35,45,90],[100,2,10,3]])
# [[25,2,10,3]
# [100,35,45,90]]
np.sort(d,axis=0)

array([[ 25,   2,  10,   3],
       [100,  35,  45,  90]])

In [13]:
e=np.array([[25,35,45,90],[100,90,25,10]])
np.sort(e,axis=1)

array([[ 25,  35,  45,  90],
       [ 10,  25,  90, 100]])

In [14]:
f=np.array([[100,250,350,1],[1000,1250,100,800]])
np.sort(f,axis=1)
# [1,100,250,350]
# [100,800,1000,1250]

array([[   1,  100,  250,  350],
       [ 100,  800, 1000, 1250]])