<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/datatypes_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

# Datatypes

# i=int
# f=float
# S-String
# U-unicode Strings
# m-timedelta
# M-datetime
# O-object
# V-Void

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
print(a.dtype)

int64


In [6]:
b=np.array(['10','20','30','40','50'])
print(b)
print(b.dtype)

['10' '20' '30' '40' '50']
<U2


In [10]:
c=np.array([1,3,4,5,6],dtype="S")

In [11]:
c

array([b'1', b'3', b'4', b'5', b'6'], dtype='|S1')

In [12]:
d=a.astype("U")
print(d)
print(d.dtype)

['1' '2' '3' '4' '5']
<U21


In [14]:
d=a.astype("bool")
print(d)
print(d.dtype)

[ True  True  True  True  True]
bool


In [15]:
# Copy & View

In [16]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [17]:
c=np.copy(a)

In [18]:
c

array([10, 20, 30, 40, 50])

In [19]:
c[0]=100

In [20]:
c

array([100,  20,  30,  40,  50])

In [21]:
a

array([10, 20, 30, 40, 50])

In [22]:
v=a.view()
print("VIEW=",v)

VIEW= [10 20 30 40 50]


In [23]:
a

array([10, 20, 30, 40, 50])

In [24]:
v

array([10, 20, 30, 40, 50])

In [25]:
v[1]=100
print(v)

[ 10 100  30  40  50]


In [26]:
a

array([ 10, 100,  30,  40,  50])

In [27]:
print("V=",v, "A=",a)

V= [ 10 100  30  40  50] A= [ 10 100  30  40  50]


In [30]:
a[1]=1000
v[0]=800
print("A=",a,"V=",v)

A= [ 800 1000   30   40   50] V= [ 800 1000   30   40   50]


In [31]:
print(a.base)
print(v.base)

None
[ 800 1000   30   40   50]
