<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/Initialization_of_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Shape(), This function returns a tuple specifying indices and no. of elements.

import numpy as np

a=np.array([10,20,30,40,50,60])
print(a)


[10 20 30 40 50 60]


In [3]:
np.shape(a)

(6,)

In [4]:
a=np.array(([[10,20,30],[40,50,60]]))
print(a)

[[10 20 30]
 [40 50 60]]


In [5]:
np.shape(a)

(2, 3)

In [11]:
a=np.array([[10,20],[30,40],[50,60]])

In [12]:
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [13]:
np.shape(a)

(3, 2)

In [14]:
a=np.array([10,20,30,40,50,60])

In [15]:
np.reshape(a, (3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [16]:
np.reshape(a,(2,3))

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [21]:
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])