<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/JoiningArrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
b=np.arange(7,13).reshape(2,3)

In [5]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a=np.arange(6).reshape(2,3)

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b=np.arange(7,13).reshape(2,3)

In [10]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [12]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
np.stack((a,b),axis=1)

array([[[ 0,  1,  2],
        [ 7,  8,  9]],

       [[ 3,  4,  5],
        [10, 11, 12]]])

In [14]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [16]:
np.dstack((a,b))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])