<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/numpy_array20may23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array=np.array(range(5))

In [2]:
array

array([0, 1, 2, 3, 4])

In [3]:
array_2d = np.array([range(5), range(5)])

In [4]:
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [5]:
array.shape


(5,)

In [6]:
array_2d.shape

(2, 5)

In [7]:
array.size

5

In [8]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [9]:
array_2d.T.shape

(5, 2)

In [10]:
array_2d.shape

(2, 5)

In [11]:
array.ndim


1

In [12]:
array_2d.ndim

2

In [13]:
array.dtype

dtype('int64')

In [14]:
array_2d.dtype

dtype('int64')

In [15]:
np.array("I, Love Python")

array('I, Love Python', dtype='<U14')

In [17]:
np.array("I Love Python").conjugate

<function ndarray.conjugate>