<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/search_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# where(), return index of given value



In [3]:
a=np.arange(10,100,10)

In [4]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
np.where(a==40)

(array([3]),)

In [7]:
a=np.array([10,20,30,20,50,800,100])

In [8]:
np.where(a==10)

(array([0]),)

In [9]:
np.where(a%10==0)

(array([0, 1, 2, 3, 4, 5, 6]),)

In [11]:
np.where(a%10 !=0)

(array([], dtype=int64),)

In [12]:
np.where(a%30==1)

(array([], dtype=int64),)

In [13]:
# searchsorted
a


array([ 10,  20,  30,  20,  50, 800, 100])

In [14]:
np.searchsorted(a,[35])

array([4])

In [15]:
np.searchsorted(a,[20])

array([1])

In [16]:
np.searchsorted(a,[60])

array([5])

In [17]:
np.searchsorted(a,[70,80,20])

array([5, 5, 1])

In [18]:
a

array([ 10,  20,  30,  20,  50, 800, 100])

In [19]:
b=np.array([10,20,30,40,50,100])

In [20]:
b

array([ 10,  20,  30,  40,  50, 100])

In [21]:
np.searchsorted(b,[25])

array([2])

In [22]:
b

array([ 10,  20,  30,  40,  50, 100])