<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/Slicing_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

In [42]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [43]:
print(a[::])

[10 20 30 40 50 60]


In [44]:
print(a[::2])

[10 30 50]


In [45]:
print("a[:4]=",a[:4])

a[:4]= [10 20 30 40]


In [46]:
print("a[-1:]=",a[-1:])

a[-1:]= [60]


In [47]:
print(a[-1::-1])

[60 50 40 30 20 10]


In [48]:
b=np.array([[10,20,30,40],[50,60,70,80]])

In [49]:
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [50]:
print(b[0,0:3])

[10 20 30]


In [51]:
print("b[1,2:]=",b[1,2:])

b[1,2:]= [70 80]


In [52]:
print(b[0:2,0:2])

[[10 20]
 [50 60]]


In [53]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [54]:
print(c)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [55]:
print(c[1,0,0:2])

[70 80]


In [56]:
print(c[1,0:2,0:2])

[[ 70  80]
 [100 110]]


In [57]:
print(c[1,1,-1::-1])

[120 110 100]


In [58]:
print(c[0:2,0:2,0:2])

[[[ 10  20]
  [ 40  50]]

 [[ 70  80]
  [100 110]]]
