<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/sort()_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=np.array([10,40,30,50])

In [4]:
np.sort(a)

array([10, 30, 40, 50])

In [5]:
b=np.array([[10,20,30],[20,10,90]])

In [6]:
b

array([[10, 20, 30],
       [20, 10, 90]])

In [7]:
np.sort(b)

array([[10, 20, 30],
       [10, 20, 90]])

In [8]:
np.sort(b,axis=0)

array([[10, 10, 30],
       [20, 20, 90]])

In [9]:
d=np.dtype([('name','S10'),('perc',float)])

In [10]:
stud=np.array([("abc",90.3),("def",95.3),("ghi",65.4)], dtype=d)

In [13]:
stud

array([(b'abc', 90.3), (b'def', 95.3), (b'ghi', 65.4)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [12]:
np.sort(stud,order="perc")

array([(b'ghi', 65.4), (b'abc', 90.3), (b'def', 95.3)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [16]:

np.sort(stud,order="name")

array([(b'abc', 90.3), (b'def', 95.3), (b'ghi', 65.4)],
      dtype=[('name', 'S10'), ('perc', '<f8')])