<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/Split_array_ipynb_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a=np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [13]:
np.split(a,3)

ValueError: ignored

In [7]:
b=np.arange(20)

In [8]:
np.split(b,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [9]:
np.split(b,5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [10]:
np.array_split(b,6)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 13]),
 array([14, 15, 16]),
 array([17, 18, 19])]

In [11]:
np.array_split(b,3)

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19])]

In [12]:
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [14]:
np.hsplit(a,2)#equalent to split

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [33]:
c=np.arange(6).reshape(2,3)

In [34]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
np.vsplit(c,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [36]:
d=np.arange(7,13).reshape(2,3)

In [38]:
d

array([[ 7,  8,  9],
       [10, 11, 12]])

In [39]:
np.vsplit(d,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]

In [45]:
np.vsplit(d,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]