<a href="https://colab.research.google.com/github/Sanjayme049/Numpy/blob/main/statistical_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[10,20,30],[50,70,60],[1,2,3]])

In [3]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [8]:
np.amin(a)

1

In [9]:
np.amax(a)

70

In [10]:
np.amin(a,axis=0)

array([1, 2, 3])

In [11]:
np.amax(a,axis=1)

array([30, 70,  3])

In [12]:
np.amin(a,axis=1)

array([10, 50,  1])

In [13]:
np.amax(a,axis=1)

array([30, 70,  3])

In [14]:
a

array([[10, 20, 30],
       [50, 70, 60],
       [ 1,  2,  3]])

In [15]:
np.average(a)

27.333333333333332

In [16]:
np.average(a,axis=0)

array([20.33333333, 30.66666667, 31.        ])

In [17]:
w=[1,2,3]

In [18]:
np.average(a,weights=w,axis=0)

array([18.83333333, 27.66666667, 26.5       ])

In [19]:
np.average(a,weights=w,axis=1)

array([23.33333333, 61.66666667,  2.33333333])

In [20]:
a

array([[10, 20, 30],
       [50, 70, 60],
       [ 1,  2,  3]])

In [21]:
np.mean(a)

27.333333333333332

In [22]:
np.mean(a,axis=0)

array([20.33333333, 30.66666667, 31.        ])

In [24]:
np.mean(a,axis=1)

array([20., 60.,  2.])

In [25]:
np.median(a) #1,2,3,10,20,30,50,60,70

20.0

In [27]:
np.median(a,axis=0)

array([10., 20., 30.])

In [28]:
np.median(a,axis=1)

array([20., 60.,  2.])

In [29]:
np.var(a)

632.2222222222223

In [30]:
np.std(a)

25.144029554194816